project:
  type: website
  output-dir: docs

website:
  title: "SBW Analytics"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ljennings12/Sport-Analytics-Blog-Workspace
        target: "blank"
      - icon: twitter
        href: https://twitter.com
        target: "blank"
format:
  html:
    theme:
      light: [flatly, theme_light.scss]
      dark: [flatly, theme_dark.scss]
    # Optional: honor user's OS preference
    respect-user-color-scheme: true
    css: styles.css



